language: ruby

bundler_args: --retry 3

install:
  # Install Jekyll and dependencies. Nokogiri for html-proofer.
  - bundle config build.nokogiri --use-system-libraries
  - bundle install

# branch whitelist
# The source branch and every branch starts with "pages-" for proposed changes
branches:
  only:
  - source
  - /pages-(.*)/

script: bundle exec rake site:deploy

env:
  global:
    secure: "jxGIGVf9SZrGoYjDKiMRmiYExovb+s4HQIswmLEdwOIJUP/vU2bbMeoWlwDI8Pvpsv6QEM+yJZcaMonVYlhIvkjwUg7vQLIYN0NeEutI2ygzqtHaido4sUUy81VDgSDYPsZ9ZGDKI7EhUJDYh7bROLHLNj3TS8r85GiksrNm710="

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
