language: ruby

bundler_args: --retry 3

install:
  # Install Jekyll and dependencies. Nokogiri for html-proofer.
  - bundle config build.nokogiri --use-system-libraries
  - bundle install

# branch whitelist
# The source branch and every branch starts with "pages-" for proposed changes
branches:
  only:
    - source
    - /pages-(.*)/

# Run rakefile prep task
before_script: bundle exec rake site:prep_deploy --quiet

# Run rakefile deploy task and a script so that travis-ci won't timeout
script: bundle exec ./summat.sh; bundle exec rake site:deploy --quiet

# Run rakefile push task
after_success: bundle exec rake site:push_all --quiet

# Global environmental variables
env:
  global:
    secure: "ZjRJN6Igf2r1Nq5JBjMeie3SdpdAFPoVb+8LEjblLLqEIaAaqFA1uC07XmOYAxpe0eDqHW0QzzFvgPOARZRGeHbRp90UZBsyOPJpa4zU5W4d8hshf+vU7w6yDIdsFVBoZOE7XigwMZX/kuu5T1FhddOCZdXx+B5wBx5EcbUr+Ds="

# Generate your secure token with the travis gem:
# 1) get Github token from your Travis CI profile page
# 2) gem install travis
# 3) travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_MAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
