language: ruby

bundler_args: --retry 3

install:
  # Install Jekyll and dependencies. Nokogiri for html-proofer.
  - bundle config build.nokogiri --use-system-libraries
  - bundle install

# branch whitelist
# The source branch and every branch starts with "pages-" for proposed changes
branches:
  only:
  - source
  - /pages-(.*)/

script: bundle exec rake site:deploy

env:
  global:
    secure: "PgH3+KOAsW4RS4El4eehTkgxeSzyalqExexlZJxtFwmAwMfAIo4KuGtRhGXqkSNb4GQ/q9dL24vCq25zFghFdCcIbgon5IOuFdCNhn1xicNXJV07c0RtvIgfIuGcRSWTW0TBTrNPzdf7txysPblI9+45hdzYYrsJC8oxwH8db+U="

# Generate your secure token with the travis gem:
#
# 1) get Github token from your Travis CI profile page
#
# 2) gem install travis
#
# 3) travis encrypt 'GIT_NAME="YOUR_USERNAME" ORG_NAME="YOUR_ORGNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
#
#    However, this will result in error: data too large - consider using travis encrypt-file or travis env set
#
#    So use:
#
#    travis encrypt 'GIT_NAME="YOUR_USERNAME" ORG_NAME="YOUR_ORGNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
