language: ruby

install:
  # Install binary pandoc from Rstudio
  # To use Pandoc, uncomment the following
  #- export PATH="$HOME/pandoc:$PATH"
  #- mkdir $HOME/pandoc
  #- curl -O https://s3.amazonaws.com/rstudio-buildtools/pandoc-1.12.3.zip
  #- unzip -j pandoc-1.12.3.zip pandoc-1.12.3/linux/debian/x86_64/pandoc
  #    -d $HOME/pandoc
  #- chmod +x $HOME/pandoc/pandoc
  #- pandoc --version

  # Install Jekyll and dependencies
  - bundle install

# branch whitelist
branches:
  only:
  - master     # test the gh-pages branch
  - gh-pages     # test the gh-pages branch
  - /pages-(.*)/ # test every branch which starts with "pages-"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  secure: "MB74xpbqTGCCJm/Au8YcYFS+uhWHRVcHf5FVqTVcNFhhRzh9xLo5WMNhaEMksGjhghW9ADwZ1vZ07+F8DtdPUZsvaNWV7yFbXPjKeAlbAJhHcMtXwjHVPBstiXITHZbxERwqbdFia22gm5EZIoLXmpp5LuzzH2KZ0Xccdd8TqUM="

script: bundle exec rake site:deploy --quiet

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
