language: ruby

bundler_args: --retry 3

install:
  # Install Jekyll and dependencies
  - bundle config build.nokogiri --use-system-libraries
  - bundle install

# branch whitelist
# The source branch and every branch starts with "pages-" for proposed changes
branches:
  only:
  - source
  - /pages-(.*)/

script: bundle exec rake site:deploy --quiet

env:
  global:
    secure: "FHFRRXsLp7fxjKeL3fiBbCgCZgWQ6C/67yAoI8Strb9pv+HD+NBUC/f50BztqesNMWKdgxMeghmrahq5WjamrUx1wpqbA69DcEiDYOqYB2uZZpJ6LfSA/4lbqUoN4DP0pd5PaL3ZsmlesxfWtjJyG4TPOU+ITgZ4oj/TMj00Hvc="

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
